services:
  - type: web
    name: ai-voice-detector
    env: python
    runtime: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: API_KEY
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /
